# Generated by Django 3.2.7 on 2021-09-20 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_employeeattendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 20, 22, 28, 43, 875246)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeattendancerecord',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
